In [ ]:
# PyTorch

In [ ]:
# Tensors - Basic unit of data representation

In [ ]:
# install torch
!pip install torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
# import torch
import torch

In [ ]:
# Create a tensor with torch
t = torch.tensor(3.)
print(t)

tensor(3.)


In [ ]:
print(t.dtype)

torch.float32


In [ ]:
# creating a vector with tensor
t1 = torch.tensor([1,2,3])
print(t1)
print(t1.dtype)

tensor([1, 2, 3])
torch.int64


In [ ]:
t2 = torch.tensor([1.,2.,3.])
print(t2)
print(t2.dtype)

tensor([1., 2., 3.])
torch.float32


In [ ]:
# create a matrix
li = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
t3 = torch.tensor(li)

In [ ]:
print(t3)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [ ]:
print(t3.shape)

torch.Size([3, 3])


In [ ]:
li = [
    [
        [1,2,3],
        [4,5,6]
    ]
]

In [ ]:
t4 = torch.tensor(li)
print(t4)
print(t4.dtype)
print(t4.shape)

tensor([[[1, 2, 3],
         [4, 5, 6]]])
torch.int64
torch.Size([1, 2, 3])


In [ ]:
t5 = torch.tensor(1.)
t6 = torch.tensor(4.)
t7 = torch.tensor(7.)

In [ ]:
t5,t6,t7

(tensor(1.), tensor(4.), tensor(7.))

In [ ]:
t5*t6

tensor(4.)

In [ ]:
t5*t6+t7

tensor(11.)

In [ ]:
!pip install pillow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np
import PIL

In [ ]:
from PIL import Image

In [ ]:
img = Image.open('/content/306677786_195402239543689_2713905191557709494_n.webp')

In [ ]:
print(img)

<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1080x1080 at 0x7FE9B4BE5E50>


In [ ]:
print(img.size)

(1080, 1080)


In [ ]:
from numpy import asarray

In [ ]:
imgarr = asarray(img)

In [ ]:
print(imgarr)

In [ ]:
imgtensor = torch.from_numpy(imgarr)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:172.)
  """Entry point for launching an IPython kernel.


In [ ]:
print(imgtensor)

tensor([[[228, 228, 228],
         [228, 228, 228],
         [228, 228, 228],
         ...,
         [167, 167, 167],
         [169, 169, 169],
         [  0,   0,   0]],

        [[228, 228, 228],
         [228, 228, 228],
         [228, 228, 228],
         ...,
         [167, 167, 167],
         [169, 169, 169],
         [  0,   0,   0]],

        [[228, 228, 228],
         [228, 228, 228],
         [228, 228, 228],
         ...,
         [167, 167, 167],
         [169, 169, 169],
         [  0,   0,   0]],

        ...,

        [[  2,   2,   2],
         [  2,   2,   2],
         [  2,   2,   2],
         ...,
         [  2,   2,   2],
         [  2,   2,   2],
         [  2,   2,   2]],

        [[  2,   2,   2],
         [  2,   2,   2],
         [  2,   2,   2],
         ...,
         [  2,   2,   2],
         [  2,   2,   2],
         [  2,   2,   2]],

        [[  2,   2,   2],
         [  2,   2,   2],
         [  2,   2,   2],
         ...,
         [  2,   2,   2],
        

In [ ]:
print(imgtensor.dtype)

torch.uint8
